#define WIFI_SSID "WIFISSID"
#define WIFI_PASS "SomePass"

#define MQTT_BROKER_ADDR "MQTTURL"
#define MQTT_BROKER_PORT 25588
#define MQTT_BROKER_CHAN "MQTTCHAN"
#define MQTT_BROKER_USER "MQTTUSER"
#define MQTT_BROKER_PASS "MQTTPASS"
